### ISSUE TITLE
Calling an RFC in a loop fails on Windows

### ISSUE THREAD

**Issue by bsrdjan** [SAP/node-rfc#11]
Calling one RFC multiple times in a loop, fails on Windows platform.  

Unit test to reproduce [STFC_CONNECTION should work in a loop](https://github.com/SAP/node-rfc/blob/master/test/test.js#L64) works on Linux and here the error message on Windows:

``` shell
1) Connection STFC_CONNECTION should work in a loop:
     Uncaught AssertionError: expected Error {
     code: 1,
     key: 'RFC_COMMUNICATION_FAILURE',
     message: LOCATION    CPIC (TCP/IP) on local host with Unicode
     ERROR          program state check for conversation 00485915
     TIME        Tue Jan 12 10:43:06 2016
     RELEASE     742
     COMPONENT   CPIC (TCP/IP) with Unicode VERSION     3
     RC          471
     MODULE      D:/depot/bas/742_COR/src/krn/si/cpic/r3cpic.c
     LINE        6220
     DETAIL      called function STSEND in state state=BUFFER_DATA2
     COUNTER    2
} to not exist
     at C:\src\node-rfc\test\test.js:69:15

2) Connection "after each" hook:
     Uncaught AssertionError: expected Error {
     code: 1,
     key: 'RFC_COMMUNICATION_FAILURE',
     message: LOCATION    CPIC (TCP/IP) on local host with Unicode
     ERROR    program state check for conversation 00485915
     TIME        Tue Jan 12 10:43:06 2016
     RELEASE     742
     COMPONENT   CPIC (TCP/IP) with Unicode
     VERSION     3
     RC          471
     MODULE      D:/depot/bas/742_COR/src/krn/si/cpic/r3cpic.c
     LINE        6220
     DETAIL      called function STSEND in state state=BUFFER_DATA2
     COUNTER     2
} to not exist
     at C:\src\node-rfc\test\test.js:69:15
```

Create this issue as a reminder to investigate in detail.

**Comment by bsrdjan** [comment]
fixed by v0.1.6
