### ISSUE TITLE
Error: The specified module could not be found. \\?\C:\Projects\NodeRFC\node_modules\node-rfc\lib\binding\sapnwrfc.node

### ISSUE THREAD

**Issue by venkas01** [SAP/node-rfc#264]
Can you please help me resolve the below issue.

C:\Projects\NodeRFC>node -p "require('node-rfc')"
C:\Projects\NodeRFC\node_modules\node-rfc\lib\wrapper\noderfc-bindings.js:46
    throw err;
    ^

Error: The specified module could not be found.
\\?\C:\Projects\NodeRFC\node_modules\node-rfc\lib\binding\sapnwrfc.node

 The SAP NW RFC SDK could not be loaded, check the installation: https://github.com/SAP/node-rfc/blob/master/doc/installation.md#sap-nwrfc-sdk-installation
environment: {
  "platform": {
    "name": "win32",
    "arch": "x64",
    "release": "10.0.19042"
  },
  "env": {
    "SAPNWRFC_HOME": "C:\\nwrfcsdk",
    "RFC_INI": "",
    "nwrfcsdk_lib_on_path": true
  },
  "versions": {
    "node": "16.17.0",
    "v8": "9.4.146.26-node.22",
    "uv": "1.43.0",
    "zlib": "1.2.11",
    "brotli": "1.0.9",
    "ares": "1.18.1",
    "modules": "93",
    "nghttp2": "1.47.0",
    "napi": "8",
    "llhttp": "6.0.7",
    "openssl": "1.1.1q+quic",
    "cldr": "41.0",
    "icu": "71.1",
    "tz": "2022a",
    "unicode": "14.0",
    "ngtcp2": "0.1.0-DEV",
    "nghttp3": "0.1.0-DEV"
  }
}

    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Projects\NodeRFC\node_modules\node-rfc\lib\wrapper\noderfc-bindings.js:36:49)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Projects\NodeRFC\node_modules\node-rfc\lib\index.js:20:14)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by venkas01** [comment]
By the way i checked if the file exists also .

![image](https://user-images.githubusercontent.com/19694797/186111617-4d8d0af5-007d-4e9d-98be-d1d628d8a852.png)

**Comment by bsrdjan** [comment]
Is SAP NWRFC SDK installed, ad per requirements: https://github.com/SAP/node-rfc#requirements?

What is the content of C:\nwrfcsdk and does the user has access to that folder?

**Comment by venkas01** [comment]
Hi Srdjan,

Good to hear from you.
Yes i have done the prerequisite  also.  

C:\nwrfcsdk\bin>rfcexec.exe
Error: Not all mandatory parameters specified
        Please start the program in the following way:
        rfcexec -t -a <program ID> -g <gateway host> -x <gateway service>
                -f <file with list of allowed commands> -s <allowed Sys ID>
The options "-t" (trace), "-f" and "-s" are optional.

Below further optional parameters are listed. You can find their
documentation in sapnwrfc.ini:
-on_cce <0, 1, 2> (On Character Conversion Error)
-cfit (Conversion Fault Indicator Token - the substitute symbol used if on_cce=2)
-keepalive (Sets the keepalive option. Default is 0.)
-delta <0, 1> (default 1, i.e. use delta-manager)
-no_compression (table compression, default is 0, i.e. compression is on)

**Comment by bsrdjan** [comment]
is it solved in the meantime?

**Comment by venkas01** [comment]
> is it solved in the meantime?

Thank you for the reply. 

Yes resolved after I re installed.

**Comment by venkas01** [comment]
Resolved.
